### ISSUE TITLE
Check 3rd party input

### ISSUE THREAD

**Issue by cedricbu** [adamruzicka/receptor-satellite#2]
In the worker, several inputs are provided by external entity (not receptor), such as hosts, text_updates, text_update_interval & text_update_full are applied without checks. These values  should probably be checked for sanity, as a safety measure (I am aware of the fact that at this point, untrusted input would lead to far more disastrous consequences on the hosts. This current issue is only aiming at protecting Receptor).

```
class Config:
    def __init__(self, text_updates = False, text_update_interval = 5000, text_update_full = True):
        self.text_updates = text_updates
        self.text_update_interval = text_update_interval
        self.text_update_full = text_update_full
```

```
class Run:
    def __init__(self, queue, remediation_id, playbook_run_id, account, hosts, playbook, config, plugin_config):
        self.queue = queue
        self.remedation_id = remediation_id
        self.playbook_run_id = playbook_run_id
        self.account = account
        self.playbook = playbook
        self.config = Config.from_raw(config)
        self.hosts = [Host(self, None, name) for name in hosts]
        self.satellite_api = SatelliteAPI.from_plugin_config(plugin_config)
```
In all of the above, I think only queue (created locally) and plugin_config (provided by receptor itself), should be considered trusted from the plugin's point of view. The rest is taken from a JSON payload provided by external source.

Examples :
* If `text_update_interval` is not a number, I suspect it might be able to trigger a backtrace, leading to a DoS in `await asyncio.sleep(self.run.config.text_update_interval / 1000)`
Also the sanity of the number should probably be checked.

* Regarding the hosts, from the plugin's point of view, it's probably feasible to send a single host name that contains ',' (e.g.: `[ "host1", "host2,secret", "host3" ]` ): this would be treated as 3 hosts by the worker, but 4 hosts by the satellite (`"host_ids": "name ^ ({})".format(','.join(hosts))`.

**Comment by adamruzicka** [comment]
Thank you for looking into this, I'll try to make the code more defensive.

**Comment by cedricbu** [comment]
sorry, I just realized I missed https://github.com/adamruzicka/receptor-satellite/pull/9 ... my bad!
:) I think this issue can be closed now.

**Comment by adamruzicka** [comment]
As long as you're satisfied with how #9 turned out :)

**Comment by cedricbu** [comment]
☺ yes, it looks good to me
